<a href="https://colab.research.google.com/github/toy00745/IBM-Assignments/blob/main/412519205139_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Basic Python** 

1. Split the string

In [1]:
s ="Hi there Sam!"

In [2]:
s.split()

['Hi', 'there', 'Sam!']

2. Use .format() to print string

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
result = "The diameter of {planet} is {diameter} Kilometres.".format(planet=planet, diameter=diameter)
print(result)

The diameter of Earth is 12742 Kilometres.


3. In this nest dictionary grab the word "Hello"

In [5]:
d={ 'k1' : [1,2,3,{"tricky":['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [7]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


**Numpy**

In [8]:
import numpy as np

4.1 Create an array of 10 zeros

In [9]:
array_zero=np.zeros(10)
print(array_zero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4.2 Create an array of 10 fives

In [10]:
array_five=np.ones(10)*5
print(array_five)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


5. Create an array of even integers from 20 to 35

In [11]:
even_int=[x for x in range(20,35,2)]
print(even_int)

[20, 22, 24, 26, 28, 30, 32, 34]


6. Create a 3x3 matrix with values ranging from 0-8

In [13]:
import numpy as np
matrix_three=np.arange(0,9).reshape(3,3)
print(matrix_three)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. Concatenate a and b

a=[1,2,3]
b=[4,5,6]

In [16]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate((a,b),axis=None))

[1 2 3 4 5 6]


**Pandas**

8. Create a dataframe with 3 rows and 2 columns

In [17]:
import pandas as pd

In [19]:
import numpy as np
array_random=np.random.randint(10,size=(3,2))
print(pd.DataFrame(array_random))

   0  1
0  2  8
1  8  3
2  2  9


9. Generate a series of dates from 1st January 2023 to 10th February 2023

In [21]:
import datetime
start_date=datetime.date(2023,1,1)
end_date=datetime.date(2023,2,10)
delta=datetime.timedelta(days=1)

while start_date <= end_date:
  print(start_date)
  start_date+=delta

2023-01-01
2023-01-02
2023-01-03
2023-01-04
2023-01-05
2023-01-06
2023-01-07
2023-01-08
2023-01-09
2023-01-10
2023-01-11
2023-01-12
2023-01-13
2023-01-14
2023-01-15
2023-01-16
2023-01-17
2023-01-18
2023-01-19
2023-01-20
2023-01-21
2023-01-22
2023-01-23
2023-01-24
2023-01-25
2023-01-26
2023-01-27
2023-01-28
2023-01-29
2023-01-30
2023-01-31
2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10


10. Convert 2D list to Data Frame

lists = [[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]

In [22]:
import pandas as pd
lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
df=pd.DataFrame(lists,columns=['S.No','Name','Value'])
print(df)

   S.No Name  Value
0     1  aaa     22
1     2  bbb     25
2     3  ccc     24
